name: PrBuild

on:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build app
        run: |
          mvn verify --no-transfer-progress
